### ISSUE TITLE
Change hook call from macro to python for prevent false error

### ISSUE THREAD

**Issue by alkabal** [linuxcnc-probe-screen/probe-screen-ng#39]
Well

I think about the best option so we can use special ohookcode routine without error checking that allow user to do all wanted with less possible issue
M2 inside hook allow user to stop t

and preserve the actual code for probing macro

Imo this is the safest way, I need to do new test with actual code but I have noticed regarding the probing sequence this is a good idea for call hook only at start off each routine 

For my use I have also add a hook end function.

what did you think ?

**Comment by kiall** [comment]
> Well
> 
> I think about the best option so we can use special ohookcode routine without error checking

The error checking is essentially asking LinuxCNC "did the last thing I do result in an system error?" - ignoring that a failure has occured would be risky at best.

> That allow user to do all wanted with less possible issue

What issues specifically? E.g the issue with `(MSG,)` was a bug in the probe screen that you found, and we fixed it now :) if there's more issues, we should fix them rather than disable error handling.

> M2 inside hook allow user to stop t
> 
> and preserve the actual code for probing macro
>
> Imo this is the safest way, I need to do new test with actual code but I have noticed regarding the probing sequence this is a good idea for call hook only at start off each routine

I'm not sure I understand this part? 


> For my use I have also add a hook end function.
> 
> what did you think ?

I'm not opposed to adding a end macro hook, but would like to understand why? - I.e. what would be useful to add at the end of the probe screen macros? 

That said, I  suspect adding a reliable macro end hook will be significantly harder than adding a start hook as there are many more places a macro can end - e.g. the actual end of the macro, anywhere an error occurs, anywhere a return statement is used.

**Comment by alkabal** [comment]
Hi

Unfortunately i have to says you are right for difficulty i have miss to think about all possible situation...

For my own hook is used for check status and allow the correct probe pin input to be connected with motion.probe-input, at start of each sequence i like to reactivate both input without regarding the status at end.

Other use can be necessary for other one that have for example a retractable touch probe

For my issue i will try soon to isolate the situation, but regarding to the do not check error is only discussed for hook and keep the error detection for real macro
Br

**Comment by alkabal** [comment]
https://github.com/linuxcnc-probe-screen/probe-screen-ng/pull/42
