### ISSUE TITLE
suggestion for popup allways on top

### ISSUE THREAD

**Issue by alkabal** [linuxcnc-probe-screen/probe-screen-ng#70]
Hi

I don't found how to implement that but imo this need to be done if possible.
https://www.google.com/search?q=gtk+set_keep_above(True)&rlz=1C1AVFC_enFR800FR800&oq=gtk+set_keep_above(True)&aqs=chrome..69i57j33i10i160.1784j1j4&sourceid=chrome&ie=UTF-8

Br

**Comment by kiall** [comment]
I've added this in 642d4d68a1f05b1d491be01fda4ae44536890e9c and verified it works fine for me - the dialogs are kept on top of the main window at all times.

**Comment by alkabal** [comment]
Hi

Thanks, that work fine but i now understand why i have failed: 

Does not work using fullscreenin .axisrc :

`"root_window.attributes('-fullscreen', True)" `

**Comment by kiall** [comment]
Ah, when you're running in fullscreen mode - I don't think it's possible.

The issue is that `set_keep_above()` will only keep it above the other GTK / gladevcp windows. It won't keep it above the AXIS / Tkinter window. 

When AXIS is set to fullscreen, the Tkinter version of "always on top" is set against the main window.

**Comment by alkabal** [comment]
Thanks a lot for information, you have very good knowledge !
